### ISSUE TITLE
Configuration fails to load for custom config file

### ISSUE THREAD

**Issue by pkout** [CoorpAcademy/serverless-plugins#10]
When the `custom` section of the `serverless.yml` file extracted to an external file like so

```
custom: ${file(./env.${self:provider.stage}.yml)}
```

the config file fails to load the configuration for the `serverless-offline-sqs` plugin.

**Comment by godu** [comment]
@pkout I don't manage to reproduce it. 

```yml
custom: ${file(./custom.yml)}
```

seems to work fine. Are you sure it isn't a `serverless` or `serverless-offline` but ?
