### ISSUE TITLE
[3.1.0] Cannot read property 'Fn::GetAtt' of undefined

### ISSUE THREAD

**Issue by poupougnac** [CoorpAcademy/serverless-plugins#109]
I have this issue while autocreating queues, probably related to this commit : 
https://github.com/CoorpAcademy/serverless-plugins/commit/0b80ee42fe512fe0646b83956667a296fa8fef84#diff-32e9d7d10726a2f50f1aea57d090602c

3.0.1 works fine.

**Comment by AdrieanKhisbe** [comment]
@poupougnac Thanks for the heads up!
I just released [v3.1.1](https://www.npmjs.com/package/serverless-offline-sqs/v/3.1.1).
Please confirm me it works for you :)
