### ISSUE TITLE
sls offline stuck on "offline: Starting Offline SQS: local/us-east-1."

### ISSUE THREAD

**Issue by MaxVynohradov** [CoorpAcademy/serverless-plugins#171]
Hi!
sls offline command stuck on "offline: Starting Offline SQS: local/us-east-1."

    "serverless-offline": "^6.8.0",
    "serverless-offline-sqs": "4.0.0", //  and the all newest

  serverless-offline-sqs:
    skipCacheInvalidation: false
    autoCreate: true
    endpoint: http://0.0.0.0:9324
    region: ${self:provider.region}
    accessKeyId: root
    secretAccessKey: root

What is the last working version of serverless-offline and serverless-offline-sqs ?

**Comment by stacks13** [comment]
It worked for me after I set environment variable `NODE_ENV` to `test` . I'm don't know if this behavior is intentional, but it would be great if it was documented.

**Comment by invaderb** [comment]
Also ran into this and setting NODE_ENV to test allows the offline to work, any other variable seems to cause offline to hang.

**Comment by joquijada** [comment]
Ran into same exact issue as others and setting `NODE_ENV=test` got rid of the problem.

**Comment by MaxVynohradov** [comment]
Got this, thank you!

**Comment by larrybotha** [comment]
Can this ticket be reopened? Requiring `NODE_ENV=test` appears to be a bug.

What's happening here is that a promise is awaited that is only resolved upon killing the serverless process. In the [`serverless-offline` docs](https://github.com/dherault/serverless-offline#usage-with-serverless-dynamodb-local-and-serverless-webpack-plugin) they differentiate between using the following two commands to start `serverless-offline`:

```bash
# will only trigger the offline:start hook in plugins
$ serverless offline

# will trigger offline:start:[init|ready|end] hooks in plugins
$ serverless offline start
```

Based on https://github.com/CoorpAcademy/serverless-plugins/blob/master/packages/serverless-offline-sqs/src/index.js#L49-L53 we have the following results:

```
# $ serverless offline
-> offline:start hook triggered
	-> calls this._startWithReady
		-> calls this.start
			-> if NODE_ENV=test, calls awaits this._listenForTermination
				-> only resolves when process is terminated
				-> blocks any further progress of serverless plugin processing
-> user kills process (ctrl-C / other)
	-> performs no cleanup

# $ serverless offline start
-> offline:start:init hook triggered
-> offline:start:ready hook triggered
	-> calls this._startWithReady
		-> calls this.start
			-> if NODE_ENV=test, calls awaits this._listenForTermination
				-> only resolves when process is terminated
				-> blocks any further processing of requests / plugin events
-> user kills process (ctrl-C / other)
	-> offline:start:end hook triggered
		-> performs cleanup
```

`NODE_ENV=test` skips the line where the unresolved promise would be called.

There doesn't appear to be a need to `async/await` on `process.on` receiving an exit signal in `_listenForTermination` - the handlers should be attached and then forgotten.

We can allow users to use either the `serverless offline` or `serverless offline start` commands by removing the promise in that function.

I can submit a PR to make this `NODE_ENV` agnostic, along with fixing any related tests - would anyone be able to review and merge a PR?

**Comment by payprmoney** [comment]
Bump. This is still an issue in 5.0.0.

**Comment by RocketSockz** [comment]
Bump. I am still having this issue as well.

**Comment by randalvance** [comment]
Bump. This is still an issue in `6.0.0`.

**Comment by lunarwtr** [comment]
Bueller
