### ISSUE TITLE
Rules for an event not taken in consideration

### ISSUE THREAD

**Issue by kyalha** [CoorpAcademy/serverless-plugins#185]
Hi !
I am using this library for testing my lambdas and event offline.
Unfortunately, it seems like the events with rules are not considered regarding the code and the result on my side.
The code there from your library:
`
    const events = service.getAllEventsInFunction(functionKey) || [];
      events.forEach(event =&gt; {        const {s3} = event;
        if (s3 &amp;&amp; functionDefinition.handler) {          s3Events.push({            functionKey,            handler: functionDefinition.handler,            s3          });        }      });`

does not consider an event with a rule such as (sample from my serverless.yml):

`    events:
      - s3:
          bucket: *********
          event: s3:ObjectCreated:Put
          rules:
            - prefix: new/
          existing: true`

with a rules - prefix on a key "new"

Could it be something considered ? Or maybe I missed something.

Also I have an other issue, my event is triggered twice... and on my staging environment with a real bucket and the same configuration, the event is triggered once.

**Comment by kyalha** [comment]
Thank you @Szarlus  for your reply and your PR! Good to hear I am not the only one seeing the problem with minio.

**Comment by Szarlus** [comment]
@kyalha yeah, the PR is there, but I am afraid that this project starts looking abandoned, it's hard to tell when/if it will ever get merged

**Comment by godu** [comment]
@Szarlus Thank you for your contribution.
@kyalha Sorry for the delay, you can use `serverless-offline-s3@5.1.0`.

**Comment by kyalha** [comment]
@Szarlus  @godu  Thanks a lot ! :-)

**Comment by Szarlus** [comment]
@godu thanks for merge :)
