### ISSUE TITLE
are these project dead?  maintained? 

### ISSUE THREAD

**Issue by bitsofinfo** [CoorpAcademy/serverless-plugins#187]
are these projects dead? maintained?  numerous issues,  prs w/  zero activity.

**Comment by Roberto-Calderon** [comment]
Use the community, there's 26 pull request at this time

**Comment by bitsofinfo** [comment]
huh? only the project committers and approve those PRs and push out fixes/tags

**Comment by bruceharrison1984** [comment]
Asking the same question nearly a year later. Seems dead to me.
