### ISSUE TITLE
How to Debug with Breakpoints

### ISSUE THREAD

**Issue by cdalton713** [CoorpAcademy/serverless-plugins#208]
Hello - I'm trying to figure out how to debug SQS handlers offline with breakpoints.  I use Webstorm; using debug mode for `NODE_ENV=local sls offline --noPrependStageInUrl` works correctly and as expected for HTTP events, but it does _not_ catch SQS events.

I've also tried attaching a debugger using `NODE_ENV=local sls offline --noPrependStageInUrl --debug=9229' and a `Attach to Node.JS/Chrome` debug configuration in Webstorm, but this debugger never attaches.  Any suggestions would be greatly appreciated!

**Comment by godu** [comment]
I use vscode to debug. You could find my debug config https://github.com/CoorpAcademy/serverless-plugins/blob/master/.vscode/launch.json and adapt it to your use case.
