### ISSUE TITLE
Error upon installing serverless-offline-sqs

### ISSUE THREAD

**Issue by EmmanDizon** [CoorpAcademy/serverless-plugins#224]
after executing "npm i serverless-offline-sqs", it produces the error below

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cico-api@1.0.0
npm ERR! Found: serverless-offline@10.3.2
npm ERR! node_modules/serverless-offline
npm ERR!   dev serverless-offline@"^10.0.2" from the root project
npm ERR! node_modules/serverless-offline-sqs
npm ERR!   serverless-offline-sqs@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\username\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Local\npm-cache\_logs\2022-10-17T08_16_39_097Z-debug-0.log

**Comment by godu** [comment]
https://github.com/CoorpAcademy/serverless-plugins/issues/217
