### ISSUE TITLE
Does not work with useSeparateProcesses

### ISSUE THREAD

**Issue by otbe** [CoorpAcademy/serverless-plugins#26]
Hi there,

I use `serverless-offline-sqs` within a serverless-offline project which is started with [`useSeparateProcesses`](https://github.com/dherault/serverless-offline#usage-and-command-line-options). This is currently the only way to get `typeorm`s connection pooling working properly while developing via serverless-offline (at least as far as I know :))

Without `useSeparateProcesses` the integration via sqs, serverkess-offline and serverless-offline-sqs works great, but breaks with `useSeparateProcesses`. I get the following exception when sending a message:
```
Serverless: my-queue (λ: messageProcessor)
(node:90487) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createExternalHandler' of undefined
    at createHandler (/node_modules/serverless-offline/src/functionHelper.js:90:19)
    at ServerlessOfflineSQS.eventHandler (/node_modules/serverless-offline-sqs/src/index.js:100:21)
```

I tried to use a configuration property like `skipCacheInvalidation`
```yml
serverless-offline-sqs:
   ...
   useSeparateProcesses: true
```
But this does not help.

I would be grateful for any advice :)

Thanks a lot!

**Comment by brunocascio** [comment]
Same issue here

**Comment by smonami** [comment]
Facing same issue

**Comment by godu** [comment]
Hi folk,

I just fix `--useSeparateProcesses` issue. Thanks to have reported to me.
