### ISSUE TITLE
severless-offline 4.10.0 breaks createLambdaContext

### ISSUE THREAD

**Issue by asprouse** [CoorpAcademy/serverless-plugins#55]
`serverless-offline 4.10.0` was released on May 5th and it changes the function signature of [createLambdaContext](https://github.com/dherault/serverless-offline/commit/f70da0b0252722cd1e2696fc5ebd2adaebd4a8e6#diff-749a8c41b399b33788d1bab873baedd7L7). This in turn breaks [serverless-offline-dynamodb-streams](https://github.com/CoorpAcademy/serverless-plugins/blob/298e7e841587a7542294ece4880125cadbb355e9/packages/serverless-offline-dynamodb-streams/src/index.js#L107). I was able to work around this using yarn's resolutions feature to pin the version to `4.9.4`.

**Comment by godu** [comment]
Thanks, you saved me a lot of time.
