### ISSUE TITLE
serverless-offline-ssm-provider - sls deploy no such file .env 

### ISSUE THREAD

**Issue by ed-sparkes** [CoorpAcademy/serverless-plugins#71]
sls deploy seems to required the file exists even though presumably this is offline plugin is meant to be used offline only, i dont want to commit my .env file as its got sensitive information on, when using sls deploy i would hope it would use ssm rather than the offline fallback 

any thoughts on this ?

thanks, Ed

**Comment by markronquillo** [comment]
The plugin should have a config where it will only be applied in a given stage e.g. dev

Right now, I just make sure that serverless-offline-ssm-provider is not included in the plugins in production.

**Comment by godu** [comment]
@ed-sparkes You're right. In the next release, `serverless-offline-ssm-provider` doesn't throws error if the file isn't present.
`serverless-offline-ssm-provider` should stay a fallback of original aws provider.
