### ISSUE TITLE
[serverless-offline-sqs] Doesn't create FIFO queue

### ISSUE THREAD

**Issue by vkartaviy** [CoorpAcademy/serverless-plugins#73]
Need to check here https://github.com/CoorpAcademy/serverless-plugins/blob/master/packages/serverless-offline-sqs/src/index.js#L164 if the name ends with `.fifo` then add `Attributes: { FifoQueue: true }`

**Comment by vkartaviy** [comment]
Unfortunately FIFO queue can't have a lambda trigger :(

**Comment by AdrieanKhisbe** [comment]
Yes indeed.

cf : https://stackoverflow.com/questions/53416890/cant-trigger-lambdas-on-sqs-fifo

**Comment by rajuashok** [comment]
Any plans to add FIFO queues? Not only is it supported for lambda triggers on FIFO queues, but I just need a way to create one locally as I'm queueing messages onto the FIFO queue via API.

**Comment by AdrieanKhisbe** [comment]
@rajuashok it's only supported since last Month...
 Cf mentionned SO issue.

And if you really want it, we are open to PRs :)

**Comment by rajuashok** [comment]
For now it's easy for me to test via deploying directly to a dev environment. If I get some time I'll see if I can send a PR. Appreciate you looking into this! Thanks.

**Comment by Letsch22** [comment]
@AdrieanKhisbe I added support for this in #107

**Comment by AdrieanKhisbe** [comment]
@Letsch22 Cool, I will try to have a look into it soon
