### ISSUE TITLE
serverless-offline-sqs doesn't work well with typescript

### ISSUE THREAD

**Issue by tomzaku** [CoorpAcademy/serverless-plugins#76]
It got some errors like this
```
(node:52370) UnhandledPromiseRejectionWarning: Error: Cannot find module '.../src/handler'
```

How can I solve this?

**Comment by tomzaku** [comment]
I know the error come from, see this line:
https://github.com/dherault/serverless-offline/blob/ec0a9a0f6a84cc2afd722d719c4680114b7ae51d/src/functionHelper.js#L234
As you can see: `require(funOptions.handlerPath)[funOptions.handlerName]`
It requires the handler pathname file expected ‘js’ but in this case is ‘ts’.
Don’t know how to fix this? Do you have any idea?

**Comment by AdrieanKhisbe** [comment]
@tomzaku 
I think you should either configure serverless handler to point on the place where put your compiled js file, or you can use the [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack) and configure it for him to tale care of compilation and linking.

Tell me if it solves your issue

**Comment by AdrieanKhisbe** [comment]
Closing as staled
