### ISSUE TITLE
[serverless-offline-sqs] Promise await in the lambda causes env variables to reset

### ISSUE THREAD

**Issue by arnas** [CoorpAcademy/serverless-plugins#83]
Hello,

I have encounter an issue that if I have a lambda function, which is only invoked via sqs messages env variables are reset after async action. 
For example if have lambda defined like this:
```js  
const main = async (event: SQSEvent, context: any) => {
  console.log(process.env.LAMBDA_ENV_VARIABLE));

  await Promise.Resolve();

  console.log(process.env.LAMBDA_ENV_VARIABLE));
};
```
the second console will output `undefined`.

It is caused by resetting`process.env` without awaiting promise that x variable produces. 
https://github.com/CoorpAcademy/serverless-plugins/blob/master/packages/serverless-offline-sqs/src/index.js#L149

https://github.com/CoorpAcademy/serverless-plugins/blob/master/packages/serverless-offline-sqs/src/index.js#L154

I would suggest to fix it like this 
```js  
    const x = handler(event, lambdaContext, lambdaContext.done);
    if (x && typeof x.then === 'function' && typeof x.catch === 'function') {
      x.then(lambdaContext.succeed)
        .catch(lambdaContext.fail)
        .then(() => {
          process.env = env;
        });
    } else if (x instanceof Error) {
      lambdaContext.fail(x);
      process.env = env;
    }
```
I could create pr if they are accepted? 

NOTE: it seems that this issue is not reproducible if lambda was invoked firstly via http event ( where serveless offline sets env ) and secondly via sqs.

**Comment by godu** [comment]
@arnas You should read that. https://github.com/CoorpAcademy/serverless-plugins/issues/20#issuecomment-487305407
